server:
  port: 8081

spring:
  profiles:
    active: header_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: header_route
          uri: http://httpbin.org:80/get
          predicates:
            - Path=/**/get/**
  profiles: header_route
